name: Deploy

on:
  pull_request:
    types: [closed]

jobs:
  deploy:
    env:
      MODULE_NAME: saferpayofficial
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Install PHP 5.6
        uses: shivammathur/setup-php@v2
        with:
          php-version: '5.6'

      - name: Build module ZIP
        # IF YOU EDIT THIS, DON'T FORGET TO EDIT release.yml
        run: |
          composer install --no-dev --optimize-autoloader --classmap-authoritative
          composer dump-autoload --no-dev --optimize --classmap-authoritative
          cp .github/.htaccess vendor/.htaccess
          rm -rf .git .github tests .php-cs-fixer.php Makefile cypress* docker-compose*.yml package.json package-lock.json .docker README.md .editorconfig .gitignore .php_cs.dist browserstack.json
          mkdir ${{ env.MODULE_NAME }}
          rsync -Rr ./ ./${{ env.MODULE_NAME }}
          chmod -R 777 ${{ env.MODULE_NAME }}/var/cache
          shopt -s extglob
          rm -r !(${{ env.MODULE_NAME }})
          find . -maxdepth 1 -type f -exec rm "{}" \;
          cd ${{ env.MODULE_NAME }} && rm -rf ${{ env.MODULE_NAME }}
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          include-hidden-files: true
          name: saferpayofficial
          path: |
            .